name: Push to Pizza

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.yaml'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: pip install
        run: pip install -r requirements.txt

      - name: Push to Pizza
        env:
          PIZZA_TOKEN: ${{ secrets.PIZZA_TOKEN }}
        run: ./redirects.py push --force
